//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string Customer_Name { get; set; }
        public string Mobile1 { get; set; }
        public Nullable<int> Gender_Id { get; set; }
        public string Address { get; set; }
        public string Mobile2 { get; set; }
        public string Guarantor_Name { get; set; }
        public string Guarantor_Mobile { get; set; }
        public string Guarantor_Address { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
