//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public string Company_Mobile { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_Person_Number { get; set; }
        public string Contact_Person_Address { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
    }
}
